complaint/cms/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "cms"
urlpatterns = [
	path('cms/index', views.Index.as_view(), name='index'),
	path('cms/login', views.Login.as_view(), name='login'),
	path('cms/logout', views.Logout.as_view(), name ='logout'),
	path('cms/register', views.Register.as_view(), name = 'register'),
	
	###############admin urls######################
	path('cms/admin/inprocesscomplaints', views.InProcessComplaints.as_view(), name='inprocesscomplaints'),
	path('cms/admin/notprocessedcomplaints',views.NotProcessedComplaints.as_view(), name ='notprocessedcomplaints'),
	path('cms/admin/closedcomplaints', views.ClosedComplaints.as_view(), name='closedcomplaints'),
	path('cms/admin/manageusers', views.ManageUsers.as_view(), name='manageusers'),
	path('cms/admin/categories', views.ManageCategories.as_view(), name = 'categories'),
	path('cms/admin/subcategories', views.ManageSubCategories.as_view(), name = 'subcategories'),
	path('cms/admin/newcategory', views.NewCategory.as_view(), name = 'newcategory'),
	path('cms/admin/newsubcategory', views.NewSubcategory.as_view(), name = 'newsubcategory'),
	path('cms/admin/changepassword', views.ChangePassword.as_view(), name = 'changepassword'),
	path('cms/admin/complaintdetails/<int:complaint_id>', views.AdminComplaintDetails.as_view(), name = 'admincomplaintdetails'),
	path('cms/admin/editcategory/<int:category_id>', views.EditCategory.as_view(), name = 'editcategory'),
	path('cms/admin/editsubcategory/<int:subcategory_id>', views.EditSubcategory.as_view(), name = 'editsubcategory'),
	path('cms/admin/updatecomplaint/<int:complaint_id>', views.UpdateState.as_view(), name = 'updatestate'),
	path('cms/admin/report', views.AdminReport.as_view(), name = 'adminreport'),
	path('cms/admin/userdetails/<path:complainant_id>', views.UserDetails.as_view(), name = 'userdetails'),


	###############user urls########################
	path('cms/users/dashboard', views.Dashboard.as_view(), name = 'dashboard'),
	path('cms/users/complainthistory', views.ComplaintHistory.as_view(), name = 'complainthistory'),
	path('cms/users/profile', views.UserProfile.as_view(), name = 'profile'),
	# path('cms/users/updateprofile/<path:complainant_id>', views.UpdateProfile.as_view(), name = 'updateprofile'),
	path('cms/users/changepassword', views.UserChangePassword.as_view(), name = 'userchangepassword'),
	# path('cms/users/newpassword', views.NewPassword.as_view(), name = 'usernewpassword'),
	path('cms/users/registercomplaint', views.RegisterComplaint.as_view(), name = 'registercomplaint'),
	path('cms/users/categories/<int:category_id>/all_json_subcategories', views.filterSubcategories.as_view(), name = 'filtersubcategories'),
	path('cms/users/complaintdetails/<int:complaint_id>', views.ComplaintDetails.as_view(), name = 'complaintdetails'),
	path('cms/users/complaintreport', views.UserReport.as_view(), name = 'complaintreport'),

	path('cms/dept', views.DepNotProcessComplaints.as_view(), name = 'department'),

	#####################department urls #################
	path('cms/department/notprocessed', views.DepNotProcessComplaints.as_view(), name = 'depnotprocessed'),
	path('cms/department/closed', views.DepClosedComplaints.as_view(), name = 'depclosed'),
	path('cms/department/inprocess', views.DepInProcessComplaints.as_view(), name = 'depinprocess'),
	path('cms/department/complaintdetails/<int:complaint_id>', views.DepComplaintDetails.as_view(), name = 'depcomplaintdetails'),
	path('cms/department/updatecomplaint/<int:complaint_id>', views.DepUpdateState.as_view(), name = 'depupdatestate'),


]

complaint/complaint/urls.py
from django.contrib import admin
from django.urls import path, include
from cms import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', include('cms.urls'))
]

complaint/cms/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Admin, Complainants, Category, Subcategory, Complaints, ComplaintRemark
class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={
        	'class': 'form-control',
        	'placeholder': 'Username'
        	 }
        ))
    # first_name = forms.CharField(max_length=150, widget=forms.TextInput(
    #     attrs={
	   #      'class': 'form-control', 
	   #      'placeholder': 'first name'
	   #      }
    #     ))
    # last_name = forms.CharField(max_length=150, widget=forms.TextInput(
    #     attrs={
    #     	'class': 'form-control',
    #     	'placeholder': 'last name'
    #     	}
    #     ))
    email = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={
        	'class': 'form-control', 
        	'type': 'email', 
        	'placeholder': 'email address'
        	}
        ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
        	'class': 'form-control',
        	'placeholder': 'password'
        	}
        ))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.ModelForm):
	username = forms.CharField(max_length = 50, widget = forms.TextInput(
			attrs ={
				'placeholder': 'UserId',
				'class':'form-control',
				'autofocus':'True'
			}
		))
	password = forms.CharField(widget = forms.PasswordInput(
			attrs = {
				'class':'form-control',
				'placeholder':'Password',
				'autofocus':'True'
			}
		))
	class Meta:
		model = User
		fields = ['username','password']

	def validate_username(self):
		pass

class Forgotpass(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(
        attrs = {
            'class':'form-control',
            'placeholder':'Password',
            'autofocus':'True'
            }
        ))
    confirm_password = forms.CharField(widget = forms.PasswordInput(
            attrs = {
                'class':'form-control',
                'placeholder':'Password',
                'autofocus':'True'
            }
        ))
    class Meta:
        model = User
        fields = ['password','confirm_password']

complaint/cms/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from . import forms
from django.http import HttpResponse, JsonResponse
from .models import Admin, Complainants, Category, Subcategory, Complaints, ComplaintRemark
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, update_session_auth_hash, authenticate
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.core.paginator import Paginator
import json
from django.core import serializers
from .utils import render_to_pdf


class Login(View):
    form_class = forms.LoginForm
    template = "cms/login.html"

    def get(self, request):
    	if request.user.is_authenticated:
        	username = request.user
        	admin = Admin.objects.filter(admin_id=username).exists()
        	complainant = Complainants.objects.filter(complainant_id=username).exists()
        	department = Category.objects.filter(category_name = username).exists()
        	print(department)
        	if admin:
        		return redirect('cms:notprocessedcomplaints')
        	elif complainant:
        		return redirect('cms:dashboard')
        	elif department:
        		return redirect('cms:depnotprocessed')
        	else:
        		pass
    	else:
        	form = self.form_class(None)
        	return render(request, self.template, {'form': form})

    def post(self, request):
    	user_name = request.POST['username']
    	password = request.POST['password']
    	user = authenticate(request, username = user_name, password = password)
    	if user is not None:
    		login(request, user)
    		admin = Admin.objects.filter(admin_id=user_name).exists()
    		complainant = Complainants.objects.filter(complainant_id=user_name).exists()
    		department = Category.objects.filter(category_name = user_name).exists()
    		if admin:
    			return redirect('cms:notprocessedcomplaints')
    		elif complainant:
    			return redirect('cms:dashboard')
    		elif department:
    			return redirect('cms:depnotprocessed')
    		else:
    			pass
    	else:
    		form = self.form_class(None)
    		message = 'Incorrect username/password'
    		context = {
    			'form' : form,
    			'message' : message
			}
    		return render(request, self.template, context)

class Logout(View):
	def get(self, request):
		logout(request)
		return redirect('cms:login')

class Register(View):
	form_class = forms.RegisterForm
	template = 'cms/register.html'

	def get(self, request):
		form = self.form_class(None)
		context = {
			'form' : form,
		}
		return render(request, self.template, context)
	def post(self, request):
		form = self.form_class(request.POST)
		# if form.is_valid():
		username = request.POST['username']
		admin = Admin.objects.filter(admin_id = username).exists()
		department = Category.objects.filter(category_name = username).exists()
		user = Complainants.objects.filter(complainant_id = username).exists()
		if admin or department or user:
			email = request.POST['email']
			password = request.POST['password']
			print(email)
			exist = User.objects.filter(username = username).exists()
			if exist:
				context = {
					'form' : form,
					'message' : "You already have an existing account",
				}
				return render(request, self.template, context)
			else:
				user = User.objects.create_user(username, email, password)
				user.save()
				return redirect('cms:login')
		else:
			context = {
				'message' : "You cannot create an account, Please contact the admin for assistance",
				'form' : form,
			}
			return render(request, self.template, context)

class Index(View):
    template = "cms/index.html"
    
    def get(self, request):
    	return render(request, self.template)

class numbers(UserPassesTestMixin, View):
	template = 'cms/admin/base.html'

	def test_func(self):
		user = request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		i_status = 'in process'
		c_status = 'closed'
		numberofinprocess_complaints = ComplaintDetails.objects.filter(status = i_status).count()
		numberofnotprocessed_complaints = ComplaintDetails.objects.filter(status__isnull = True).count()
		numberofclosed_complaints = ComplaintDetails.objects.filter(status = c_status).count()
		context = {
			'numberofinprocess_complaints' : numberofinprocess_complaints,
			'numberofnotprocessed_complaints' : numberofnotprocessed_complaints,
			'numberofclosed_complaints' : numberofclosed_complaints
			}
		print(context)
		return render(request, self.template, context)

class InProcessComplaints(UserPassesTestMixin, View):
	login_url = settings.LOGIN_URL
	template = 'cms/admin/inprocess-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		status = 'in process'
		inprocess_complaints = Complaints.objects.filter(status = status)
		context = {
			'inprocess_complaints': inprocess_complaints
			}
		return render(request, self.template, context)


class NotProcessedComplaints(UserPassesTestMixin, View):
	template = 'cms/admin/notprocessed-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		notprocessed_complaints = Complaints.objects.filter(status__isnull = True)
		context = {
			'notprocessed_complaints': notprocessed_complaints
			}
		return render(request, self.template, context)


class ClosedComplaints(UserPassesTestMixin, View):
	template = 'cms/admin/closed-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		status = 'closed'
		closed_complaints = Complaints.objects.filter(status = status)
		context = {
			'closed_complaints': closed_complaints
			}
		return render(request, self.template, context)


class ManageUsers(UserPassesTestMixin, View):
	template = 'cms/admin/manage-users.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		complainants = Complainants.objects.all()
		context = {
			'complainants': complainants
			}
		return render(request, self.template, context)


class ManageCategories(UserPassesTestMixin, View):
	template = 'cms/admin/category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		categories = Category.objects.all()
		context = {
			'categories': categories	
			}
		return render(request, self.template, context)


class NewCategory(UserPassesTestMixin, View):
	template = 'cms/admin/category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def post(self, request):
		new_cat = request.POST.get('category')
		cat_description = request.POST.get('description')
		Category.objects.create(category_name = new_cat, category_description = cat_description)
		categories = Category.objects.all()
		context = {
			'categories': categories	
			}
		return render(request, self.template, context)


class ManageSubCategories(UserPassesTestMixin, View):
	template = 'cms/admin/subcategory.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		subcategories = Subcategory.objects.all()
		categories = Category.objects.all()
		context = {
			'subcategories': subcategories,
			'categories': categories	
			}
		return render(request, self.template, context)

class NewSubcategory(UserPassesTestMixin, View):
	template = 'cms/admin/subcategory.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def post(self, request):
		print(request.GET)
		print(request.POST)
		cat_id = request.POST.get('category')
		subcat_name = request.POST.get('subcategory')
		Subcategory.objects.create(category_id_id = cat_id,subcategory_name = subcat_name)
		subcategories = Subcategory.objects.all()
		categories = Category.objects.all()
		context = {
			'subcategories': subcategories,
			'categories': categories	
			}
		return render(request, self.template, context)

class ChangePassword(UserPassesTestMixin, View):
	template = 'cms/admin/change-password.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		return render(request, self.template)

class AdminComplaintDetails(UserPassesTestMixin, View):
	template = 'cms/admin/complaint-details.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request, complaint_id):
		cmpl_details = Complaints.objects.filter(complaint_id = complaint_id)
		cmpl_remark =  ComplaintRemark.objects.filter(complaint_id = complaint_id)
		if cmpl_remark:
			for rmrk in cmpl_remark:
				remark = rmrk.remark
				remarkdate = rmrk.remark_date
		else:
			remark = "No remark"
			remarkdate = "No remark"

		context = {
			'cmpl_details' : cmpl_details,
			'complaint_id' : complaint_id,
			'remark' : remark,
			'remarkdate' : remarkdate,
		}
		return render(request, self.template, context)

class EditCategory(UserPassesTestMixin, View):
	template = 'cms/admin/edit-category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request, category_id):
		category = Category.objects.filter(category_id = category_id)
		context = {
			'category' : category
		}
		return render(request, self.template, context)

	def post(self, request, category_id):
		cat_name = request.POST.get('category')
		cat_description = request.POST.get('description')

complaint/cms/templates/cms/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Complaint Management System</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="{% static  'cms/bootstrap-3.3.6/js/bootstrap.min.js'%}"></script>
    <script src="{% static  'cms/jquery-3.2.1.min.js'%}"></script>
    <link rel="stylesheet" href="{% static  'cms/bootstrap-3.3.6/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static  'cms/Font-Awesome-master/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static  'cms/css/half-slider.css'%}">
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">COMPLAINT MANAGEMENT </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'cms:login' %}">User Login</a>
                    </li>
                    <li>
                        <a href="{% url 'cms:register' %}">User Registration</a>
                    </li>
                    <li>
                        <a href="{% url 'cms:login' %}">admin</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Half Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">

            <div class="item active">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('{% static "cms/images/c2.jpg"%}');"></div>
                <div class="carousel-caption">

                </div>
            </div>
            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('{% static "cms/images/c10.jpg"%}');"></div>
                <div class="carousel-caption">

                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>

    <!-- Page Content -->
    <div class="container">

        <div class="row" style="padding-top: 16px;">
            <div class="col-lg-12">
                <div class="com"><h2><b>UNIVERSITY OF ELDORET COMPLAINT SYSTEM</b></h2>
                <p><h2>The Easiest Way To Complain Online </h2><br> <b><i>Tired off getting ripped off? Fight back and file a customer complaint now.Sign Up Today And You Can Leave Complaints on various topics/departments.</b> </i></p></div>

            </div>
        </div>
        <style>.com{text-align: center;} </style>
        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2017-Brought to You By <a href="https://uoeld.ac.ke/">University of Eldoret</a> </p>
                </div>
            </div>
            <!-- /.row -->
        </footer>
        <style> .col-lg-12{text-align: center; border: 1px solid black;}</style>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static  'cms/jquery-3.2.1.min.js'%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static  'cms/bootstrap-3.3.6/js/bootstrap.min.js'%}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

complaint/cms/templates/cms/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>{% block title %}CMS | Login{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static  'cms/users/assets/css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static  'cms/users/assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />  
    <!-- Custom styles for this template -->
    <link href="{% static  'cms/users/assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static  'cms/users/assets/css/style-responsive.css' %}" rel="stylesheet">
<script type="text/javascript">
function valid()
{
 if(document.forgot.password.value!= document.forgot.confirmpassword.value)
{
alert("Password and Confirm Password Field do not match  !!");
document.forgot.confirmpassword.focus();
return false;
}
return true;
}
</script>
  </head>

<body>
{% block content %}
	<div id="login-page">    
	  	<div class="container">
	        <form class="form-login" action="{% url 'cms:login' %}" method="post" role="form">
	         	<h2 class="form-login-heading">sign in now</h2>
                {% if message %}
                <div class="alert alert-danger" style="padding-top : 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ message }}</strong> 
                </div>
                {% endif %}
	         	<div class="login-wrap">
	                {% csrf_token%}
	                {{form}}
	                <label class="checkbox">
		                <span class="pull-right">
		                    <a data-toggle="modal" href="login.html#myModal"> Forgot Password?</a>
		
		                </span>
		            </label>
		            <button class="btn btn-theme btn-block" name="submit" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
		            <hr>
	            
            </form>
        		<div class="registration">
	                Don't have an account yet?<br/>
	                <a class="" href="{% url 'cms:register' %}">
	                    Create an account
	                </a>
	            </div>
	            </div>
	  	</div>
	</div>
{% endblock %}
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static  'cms/users/assets/js/jquery.js' %}"></script>
    <script src="{% static  'cms/users/assets/js/bootstrap.min.js' %}"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="{% static  'cms/users/assets/js/jquery.backstretch.min.js' %}"></script>
    <script>
        $.backstretch("{% static  'cms/users/assets/img/login-bg.jpg' %}", {speed: 500});
    </script>


  </body>
</html>

complaint/cms/templates/cms/register.html
{% extends 'cms/login.html' %}
{% load static %}
{% block title %}CMS | Register{% endblock %}
{% block content %}

<div id="login-page">
    <div class="container">

        <form class="form-login" method="post">
            <h2 class="form-login-heading">User Registration</h2>
            {% if message %}
                <div class="alert alert-danger" style="padding-top : 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ message }}</strong> 
                </div>
            {% endif %}
            <div class="login-wrap">
                {% csrf_token %}
                {{form}}
                <br>
                <button class="btn btn-theme btn-block"  type="submit" name="submit" id="submit"><i class="fa fa-user"></i> Register</button>
                <hr>

                <div class="registration">
                    Already Registered<br/>
                    <a class="" href="{% url 'cms:login' %}">
                    Sign in
                    </a>
                </div>
            </div>
        </form> 
    </div>
</div>
{% endblock %}