complaint/cms/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "cms"
urlpatterns = [
	path('cms/index', views.Index.as_view(), name='index'),
	path('cms/login', views.Login.as_view(), name='login'),
	path('cms/logout', views.Logout.as_view(), name ='logout'),
	path('cms/register', views.Register.as_view(), name = 'register'),
	
	###############admin urls######################
	path('cms/admin/inprocesscomplaints', views.InProcessComplaints.as_view(), name='inprocesscomplaints'),
	path('cms/admin/notprocessedcomplaints',views.NotProcessedComplaints.as_view(), name ='notprocessedcomplaints'),
	path('cms/admin/closedcomplaints', views.ClosedComplaints.as_view(), name='closedcomplaints'),
	path('cms/admin/manageusers', views.ManageUsers.as_view(), name='manageusers'),
	path('cms/admin/categories', views.ManageCategories.as_view(), name = 'categories'),
	path('cms/admin/subcategories', views.ManageSubCategories.as_view(), name = 'subcategories'),
	path('cms/admin/newcategory', views.NewCategory.as_view(), name = 'newcategory'),
	path('cms/admin/newsubcategory', views.NewSubcategory.as_view(), name = 'newsubcategory'),
	path('cms/admin/changepassword', views.ChangePassword.as_view(), name = 'changepassword'),
	path('cms/admin/complaintdetails/<int:complaint_id>', views.AdminComplaintDetails.as_view(), name = 'admincomplaintdetails'),
	path('cms/admin/editcategory/<int:category_id>', views.EditCategory.as_view(), name = 'editcategory'),
	path('cms/admin/editsubcategory/<int:subcategory_id>', views.EditSubcategory.as_view(), name = 'editsubcategory'),
	path('cms/admin/updatecomplaint/<int:complaint_id>', views.UpdateState.as_view(), name = 'updatestate'),
	path('cms/admin/report', views.AdminReport.as_view(), name = 'adminreport'),
	path('cms/admin/userdetails/<path:complainant_id>', views.UserDetails.as_view(), name = 'userdetails'),


	###############user urls########################
	path('cms/users/dashboard', views.Dashboard.as_view(), name = 'dashboard'),
	path('cms/users/complainthistory', views.ComplaintHistory.as_view(), name = 'complainthistory'),
	path('cms/users/profile', views.UserProfile.as_view(), name = 'profile'),
	# path('cms/users/updateprofile/<path:complainant_id>', views.UpdateProfile.as_view(), name = 'updateprofile'),
	path('cms/users/changepassword', views.UserChangePassword.as_view(), name = 'userchangepassword'),
	# path('cms/users/newpassword', views.NewPassword.as_view(), name = 'usernewpassword'),
	path('cms/users/registercomplaint', views.RegisterComplaint.as_view(), name = 'registercomplaint'),
	path('cms/users/categories/<int:category_id>/all_json_subcategories', views.filterSubcategories.as_view(), name = 'filtersubcategories'),
	path('cms/users/complaintdetails/<int:complaint_id>', views.ComplaintDetails.as_view(), name = 'complaintdetails'),
	path('cms/users/complaintreport', views.UserReport.as_view(), name = 'complaintreport'),

	path('cms/dept', views.DepNotProcessComplaints.as_view(), name = 'department'),

	#####################department urls #################
	path('cms/department/notprocessed', views.DepNotProcessComplaints.as_view(), name = 'depnotprocessed'),
	path('cms/department/closed', views.DepClosedComplaints.as_view(), name = 'depclosed'),
	path('cms/department/inprocess', views.DepInProcessComplaints.as_view(), name = 'depinprocess'),
	path('cms/department/complaintdetails/<int:complaint_id>', views.DepComplaintDetails.as_view(), name = 'depcomplaintdetails'),
	path('cms/department/updatecomplaint/<int:complaint_id>', views.DepUpdateState.as_view(), name = 'depupdatestate'),


]

complaint/complaint/urls.py
from django.contrib import admin
from django.urls import path, include
from cms import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', include('cms.urls'))
]

complaint/cms/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Admin, Complainants, Category, Subcategory, Complaints, ComplaintRemark
class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={
        	'class': 'form-control',
        	'placeholder': 'Username'
        	 }
        ))
    # first_name = forms.CharField(max_length=150, widget=forms.TextInput(
    #     attrs={
	   #      'class': 'form-control', 
	   #      'placeholder': 'first name'
	   #      }
    #     ))
    # last_name = forms.CharField(max_length=150, widget=forms.TextInput(
    #     attrs={
    #     	'class': 'form-control',
    #     	'placeholder': 'last name'
    #     	}
    #     ))
    email = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={
        	'class': 'form-control', 
        	'type': 'email', 
        	'placeholder': 'email address'
        	}
        ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
        	'class': 'form-control',
        	'placeholder': 'password'
        	}
        ))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.ModelForm):
	username = forms.CharField(max_length = 50, widget = forms.TextInput(
			attrs ={
				'placeholder': 'UserId',
				'class':'form-control',
				'autofocus':'True'
			}
		))
	password = forms.CharField(widget = forms.PasswordInput(
			attrs = {
				'class':'form-control',
				'placeholder':'Password',
				'autofocus':'True'
			}
		))
	class Meta:
		model = User
		fields = ['username','password']

	def validate_username(self):
		pass

class Forgotpass(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(
        attrs = {
            'class':'form-control',
            'placeholder':'Password',
            'autofocus':'True'
            }
        ))
    confirm_password = forms.CharField(widget = forms.PasswordInput(
            attrs = {
                'class':'form-control',
                'placeholder':'Password',
                'autofocus':'True'
            }
        ))
    class Meta:
        model = User
        fields = ['password','confirm_password']

complaint/cms/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from . import forms
from django.http import HttpResponse, JsonResponse
from .models import Admin, Complainants, Category, Subcategory, Complaints, ComplaintRemark
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, update_session_auth_hash, authenticate
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.core.paginator import Paginator
import json
from django.core import serializers
from .utils import render_to_pdf


class Login(View):
    form_class = forms.LoginForm
    template = "cms/login.html"

    def get(self, request):
    	if request.user.is_authenticated:
        	username = request.user
        	admin = Admin.objects.filter(admin_id=username).exists()
        	complainant = Complainants.objects.filter(complainant_id=username).exists()
        	department = Category.objects.filter(category_name = username).exists()
        	print(department)
        	if admin:
        		return redirect('cms:notprocessedcomplaints')
        	elif complainant:
        		return redirect('cms:dashboard')
        	elif department:
        		return redirect('cms:depnotprocessed')
        	else:
        		pass
    	else:
        	form = self.form_class(None)
        	return render(request, self.template, {'form': form})

    def post(self, request):
    	user_name = request.POST['username']
    	password = request.POST['password']
    	user = authenticate(request, username = user_name, password = password)
    	if user is not None:
    		login(request, user)
    		admin = Admin.objects.filter(admin_id=user_name).exists()
    		complainant = Complainants.objects.filter(complainant_id=user_name).exists()
    		department = Category.objects.filter(category_name = user_name).exists()
    		if admin:
    			return redirect('cms:notprocessedcomplaints')
    		elif complainant:
    			return redirect('cms:dashboard')
    		elif department:
    			return redirect('cms:depnotprocessed')
    		else:
    			pass
    	else:
    		form = self.form_class(None)
    		message = 'Incorrect username/password'
    		context = {
    			'form' : form,
    			'message' : message
			}
    		return render(request, self.template, context)

class Logout(View):
	def get(self, request):
		logout(request)
		return redirect('cms:login')

class Register(View):
	form_class = forms.RegisterForm
	template = 'cms/register.html'

	def get(self, request):
		form = self.form_class(None)
		context = {
			'form' : form,
		}
		return render(request, self.template, context)
	def post(self, request):
		form = self.form_class(request.POST)
		# if form.is_valid():
		username = request.POST['username']
		admin = Admin.objects.filter(admin_id = username).exists()
		department = Category.objects.filter(category_name = username).exists()
		user = Complainants.objects.filter(complainant_id = username).exists()
		if admin or department or user:
			email = request.POST['email']
			password = request.POST['password']
			print(email)
			exist = User.objects.filter(username = username).exists()
			if exist:
				context = {
					'form' : form,
					'message' : "You already have an existing account",
				}
				return render(request, self.template, context)
			else:
				user = User.objects.create_user(username, email, password)
				user.save()
				return redirect('cms:login')
		else:
			context = {
				'message' : "You cannot create an account, Please contact the admin for assistance",
				'form' : form,
			}
			return render(request, self.template, context)

class Index(View):
    template = "cms/index.html"
    
    def get(self, request):
    	return render(request, self.template)

class numbers(UserPassesTestMixin, View):
	template = 'cms/admin/base.html'

	def test_func(self):
		user = request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		i_status = 'in process'
		c_status = 'closed'
		numberofinprocess_complaints = ComplaintDetails.objects.filter(status = i_status).count()
		numberofnotprocessed_complaints = ComplaintDetails.objects.filter(status__isnull = True).count()
		numberofclosed_complaints = ComplaintDetails.objects.filter(status = c_status).count()
		context = {
			'numberofinprocess_complaints' : numberofinprocess_complaints,
			'numberofnotprocessed_complaints' : numberofnotprocessed_complaints,
			'numberofclosed_complaints' : numberofclosed_complaints
			}
		print(context)
		return render(request, self.template, context)

class InProcessComplaints(UserPassesTestMixin, View):
	login_url = settings.LOGIN_URL
	template = 'cms/admin/inprocess-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		status = 'in process'
		inprocess_complaints = Complaints.objects.filter(status = status)
		context = {
			'inprocess_complaints': inprocess_complaints
			}
		return render(request, self.template, context)


class NotProcessedComplaints(UserPassesTestMixin, View):
	template = 'cms/admin/notprocessed-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		notprocessed_complaints = Complaints.objects.filter(status__isnull = True)
		context = {
			'notprocessed_complaints': notprocessed_complaints
			}
		return render(request, self.template, context)


class ClosedComplaints(UserPassesTestMixin, View):
	template = 'cms/admin/closed-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		status = 'closed'
		closed_complaints = Complaints.objects.filter(status = status)
		context = {
			'closed_complaints': closed_complaints
			}
		return render(request, self.template, context)


class ManageUsers(UserPassesTestMixin, View):
	template = 'cms/admin/manage-users.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		complainants = Complainants.objects.all()
		context = {
			'complainants': complainants
			}
		return render(request, self.template, context)


class ManageCategories(UserPassesTestMixin, View):
	template = 'cms/admin/category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		categories = Category.objects.all()
		context = {
			'categories': categories	
			}
		return render(request, self.template, context)


class NewCategory(UserPassesTestMixin, View):
	template = 'cms/admin/category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def post(self, request):
		new_cat = request.POST.get('category')
		cat_description = request.POST.get('description')
		Category.objects.create(category_name = new_cat, category_description = cat_description)
		categories = Category.objects.all()
		context = {
			'categories': categories	
			}
		return render(request, self.template, context)


class ManageSubCategories(UserPassesTestMixin, View):
	template = 'cms/admin/subcategory.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		subcategories = Subcategory.objects.all()
		categories = Category.objects.all()
		context = {
			'subcategories': subcategories,
			'categories': categories	
			}
		return render(request, self.template, context)

class NewSubcategory(UserPassesTestMixin, View):
	template = 'cms/admin/subcategory.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def post(self, request):
		print(request.GET)
		print(request.POST)
		cat_id = request.POST.get('category')
		subcat_name = request.POST.get('subcategory')
		Subcategory.objects.create(category_id_id = cat_id,subcategory_name = subcat_name)
		subcategories = Subcategory.objects.all()
		categories = Category.objects.all()
		context = {
			'subcategories': subcategories,
			'categories': categories	
			}
		return render(request, self.template, context)

class ChangePassword(UserPassesTestMixin, View):
	template = 'cms/admin/change-password.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		return render(request, self.template)

class AdminComplaintDetails(UserPassesTestMixin, View):
	template = 'cms/admin/complaint-details.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request, complaint_id):
		cmpl_details = Complaints.objects.filter(complaint_id = complaint_id)
		cmpl_remark =  ComplaintRemark.objects.filter(complaint_id = complaint_id)
		if cmpl_remark:
			for rmrk in cmpl_remark:
				remark = rmrk.remark
				remarkdate = rmrk.remark_date
		else:
			remark = "No remark"
			remarkdate = "No remark"

		context = {
			'cmpl_details' : cmpl_details,
			'complaint_id' : complaint_id,
			'remark' : remark,
			'remarkdate' : remarkdate,
		}
		return render(request, self.template, context)

class EditCategory(UserPassesTestMixin, View):
	template = 'cms/admin/edit-category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request, category_id):
		category = Category.objects.filter(category_id = category_id)
		context = {
			'category' : category
		}
		return render(request, self.template, context)

	def post(self, request, category_id):
		cat_name = request.POST.get('category')
		cat_description = request.POST.get('description')

complaint/cms/templates/cms/admin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} CMS | Admin {% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block links %}
    <link href="{% static  'cms/admin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'cms/admin/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
    <link href="{% static  'cms/admin/css/theme.css' %}" rel="stylesheet">
    <link href="{% static  'cms/admin/images/icons/css/font-awesome.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body>
    <div class="navbar navbar-fixed-top" style="background-color: black;">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <i class="icon-reorder shaded"></i>
                </a>

                <a class="brand" href="index.html">
                    CMS | Admin
                </a>

                <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav pull-right">
                        <li><a href="#">
                            Admin
                            </a></li>
                        <li class="nav-user dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% static 'cms/admin/images/user.png' %}" class="nav-avatar" />
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'cms:changepassword' %}">Change Password</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'cms:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.nav-collapse -->
            </div>
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->

<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="span3">
                <div class="sidebar">
                    <ul class="widget widget-menu unstyled">
                        <li>
                            <a class="collapsed" data-toggle="collapse" href="#togglePages">
                                <i class="menu-icon icon-cog"></i>
                                <i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right"></i>
                                Manage Complaint
                            </a>
                            <ul id="togglePages" class="collapse unstyled">
                                <li>
                                    <a href="{% url 'cms:notprocessedcomplaints' %}">
                                      <i class="icon-tasks"></i>
                                      Not Process Yet Complaint
                                      <b class="label orange pull-right">
                                      {{ numberofnotprocessed_complaints }}</b>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'cms:inprocesscomplaints' %}">
                                      <i class="icon-tasks"></i>
                                      InProcess Complaint
                                      <b class="label orange pull-right">
                                      {{ numberofinprocess_complaints }}</b>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'cms:closedcomplaints' %}">
                                      <i class="icon-inbox"></i>
                                      Closed Complaints
                                  <b class="label green pull-right">
                                  {{ numberofclosed_complaints }}</b>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        
                        <li>
                            <a href="{% url 'cms:manageusers' %}">
                                <i class="menu-icon icon-group"></i>
                                Manage users
                            </a>
                        </li>
                        
                        <li>
                            <a href="{% url 'cms:adminreport' %}">
                                <i class="menu-icon icon-group"></i>
                                View Reports
                            </a>
                        </li>
                    </ul>
                    <ul class="widget widget-menu unstyled">
                        <li>
                            <a href="{% url 'cms:categories' %}">
                                <i class="menu-icon icon-tasks"></i> 
                                Add Category 
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'cms:subcategories' %}">
                                <i class="menu-icon icon-tasks"></i>
                                Add Sub-Category 
                            </a>
                        </li>
                    </ul>

                    <ul class="widget widget-menu unstyled">
                        <li>
                            <a href="user-logs.php">
                                <i class="menu-icon icon-tasks"></i>
                                User Login Log 
                            </a>
                        </li>
                        
                        <li>
                            <a href="{% url  'cms:logout' %}">
                                <i class="menu-icon icon-signout"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div><!--/.sidebar-->
            </div><!--/.span3-->    
            <div class="span9">
                <div class="content">
                    {% block content %}
                    <div class="module">
                        <div class="module-head">
                            <h3>yo</h3>
                        </div>
                    </div>
                    {% endblock %}
                </div><!--/.content-->
            </div><!--/.span9-->
        </div>
    </div><!--/.container-->
</div><!--/.wrapper-->

{% block scripts %}
<script src="{% static 'cms/admin/scripts/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'cms/admin/scripts/jquery-ui-1.10.1.custom.min.js' %}" type="text/javascript"></script>
<script src="{% static 'cms/admin/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script> 
{% endblock %}
</body>

</html>

complaint/cms/templates/cms/admin/category.html
{% extends 'cms/admin/base.html' %}
{% load static %}
{% block title %}Add Category{% endblock %}
{% block links %}
	<link type="text/css" href="{% static 'cms/admin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link type="text/css" href="{% static 'cms/admin/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
	<link type="text/css" href="{% static 'cms/admin/css/theme.css' %}" rel="stylesheet">
	<link type="text/css" href="{% static 'cms/admin/images/icons/css/font-awesome.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="module">
	<div class="module-head">
	<h3>Category</h3>
	</div>
	<div class="module-body">

		<!-- 									<?php if(isset($_POST['submit']))
		{?>
		<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<strong>Well done!</strong>	<?php echo htmlentities($_SESSION['msg']);?><?php echo htmlentities($_SESSION['msg']="");?>
		</div>
		<?php } ?>


		<?php if(isset($_GET['del']))
		{?>
		<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<strong>Oh snap!</strong> 	<?php echo htmlentities($_SESSION['delmsg']);?><?php echo htmlentities($_SESSION['delmsg']="");?>
		</div>
		<?php } ?> -->

		<br />

		<form action="./newcategory" class="form-horizontal row-fluid" name="Category" method="post" >{% csrf_token %}
			<div class="control-group">
				<label class="control-label" for="basicinput">Category Name</label>
				<div class="controls">
					<input type="text" placeholder="Enter category Name"  name="category" class="span8 tip" required>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="basicinput">Description</label>
				<div class="controls">
					<textarea class="span8" name="description" rows="5"></textarea>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<button type="submit" name="submit" class="btn">Create</button>
				</div>
			</div>
		</form>
	</div>
</div>


<div class="module">
	<div class="module-head">
		<h3>Manage Categories</h3>
	</div>
	<div class="module-body table">
		<table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display" width="100%">
			<thead>
				<tr>
					<th>#</th>
					<th>Category</th>
					<th>Description</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for category in categories %}
				<tr>
					<td>{{category.category_id}}</td>
					<td>{{category.category_name}}</td>
					<td>{{category.category_description}}</td>
					<td>
					<a href="{% url 'cms:editcategory' category.category_id %}" ><i class="icon-edit" title="Edit category"></i></a>
					<a href="category.php?id=<?php echo $row['id']?>&del=delete" onClick="return confirm('Are you sure you want to delete?')"><i class="icon-remove-sign" title="Delete category"></i></a></td>
				</tr>
				{% endfor %}
			</tbody>
			</table>
	</div>
</div>	
{% endblock %}
{% block scripts %}
	<script src="{% static 'cms/admin/scripts/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/scripts/jquery-ui-1.10.1.custom.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/scripts/flot/jquery.flot.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/scripts/datatables/jquery.dataTables.js' %}"></script>
	<script>
		$(document).ready(function() {
			$('.datatable-1').dataTable();
			$('.dataTables_paginate').addClass("btn-group datatable-pagination");
			$('.dataTables_paginate > a').wrapInner('<span />');
			$('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
			$('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
		} );
	</script>
{% endblock %}

complaint/cms/templates/cms/admin/closed-complaints.html
{% extends 'cms/admin/base.html' %}
{% load static %}
{% block title %}Closed Complaints{% endblock %}
{% block links %}
	<link type="text/css" href="{% static 'cms/admin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link type="text/css" href="{% static 'cms/admin/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
	<link type="text/css" href="{% static 'cms/admin/css/theme.css' %}" rel="stylesheet">
	<link type="text/css" href="{% static 'cms/admin/images/icons/css/font-awesome.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
	<div class="module">
							<div class="module-head">
								<h3>Closed Complaints</h3>
							</div>
							<div class="module-body table">


							
								<table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display" >
									<thead>
										<tr>
											<th>Complaint No</th>
											<th>complainant Name</th>
											<th>Reg Date</th>
											<th>Status</th>
											
											<th>Action</th>
											
										
										</tr>
									</thead>
								
<tbody>
										{% for complaint in closed_complaints %}
										<tr>
											<td>{{ complaint.complaint_id }}</td>
											<td>{{ complaint.complaint_type }}</td>
											<td>{{ complaint.reg_date }}</td>
										
											<td><button type="button" class="btn btn-success">Closed</button></td>
											
											<td><a href="{% url 'cms:admincomplaintdetails' complaint.complaint_id %}"> View Details</a> 
											</td>
										</tr>
										{% endfor %}

										<?php  } ?>
										</tbody>
								</table>
							</div>
						</div>
{% endblock %}
{% block scripts %}
	<script src="{% static 'cms/admin/scripts/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/scripts/jquery-ui-1.10.1.custom.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/scripts/flot/jquery.flot.js' %}" type="text/javascript"></script>
	<script src="{% static 'cms/admin/scripts/datatables/jquery.dataTables.js' %}"></script>
	<script>
		$(document).ready(function() {
			$('.datatable-1').dataTable();
			$('.dataTables_paginate').addClass("btn-group datatable-pagination");
			$('.dataTables_paginate > a').wrapInner('<span />');
			$('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
			$('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
		} );
	</script>
{% endblock %}