complaint/cms/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "cms"
urlpatterns = [
	path('cms/index', views.Index.as_view(), name='index'),
	path('cms/login', views.Login.as_view(), name='login'),
	path('cms/logout', views.Logout.as_view(), name ='logout'),
	path('cms/register', views.Register.as_view(), name = 'register'),
	
	###############admin urls######################
	path('cms/admin/inprocesscomplaints', views.InProcessComplaints.as_view(), name='inprocesscomplaints'),
	path('cms/admin/notprocessedcomplaints',views.NotProcessedComplaints.as_view(), name ='notprocessedcomplaints'),
	path('cms/admin/closedcomplaints', views.ClosedComplaints.as_view(), name='closedcomplaints'),
	path('cms/admin/manageusers', views.ManageUsers.as_view(), name='manageusers'),
	path('cms/admin/categories', views.ManageCategories.as_view(), name = 'categories'),
	path('cms/admin/subcategories', views.ManageSubCategories.as_view(), name = 'subcategories'),
	path('cms/admin/newcategory', views.NewCategory.as_view(), name = 'newcategory'),
	path('cms/admin/newsubcategory', views.NewSubcategory.as_view(), name = 'newsubcategory'),
	path('cms/admin/changepassword', views.ChangePassword.as_view(), name = 'changepassword'),
	path('cms/admin/complaintdetails/<int:complaint_id>', views.AdminComplaintDetails.as_view(), name = 'admincomplaintdetails'),
	path('cms/admin/editcategory/<int:category_id>', views.EditCategory.as_view(), name = 'editcategory'),
	path('cms/admin/editsubcategory/<int:subcategory_id>', views.EditSubcategory.as_view(), name = 'editsubcategory'),
	path('cms/admin/updatecomplaint/<int:complaint_id>', views.UpdateState.as_view(), name = 'updatestate'),
	path('cms/admin/report', views.AdminReport.as_view(), name = 'adminreport'),
	path('cms/admin/userdetails/<path:complainant_id>', views.UserDetails.as_view(), name = 'userdetails'),


	###############user urls########################
	path('cms/users/dashboard', views.Dashboard.as_view(), name = 'dashboard'),
	path('cms/users/complainthistory', views.ComplaintHistory.as_view(), name = 'complainthistory'),
	path('cms/users/profile', views.UserProfile.as_view(), name = 'profile'),
	# path('cms/users/updateprofile/<path:complainant_id>', views.UpdateProfile.as_view(), name = 'updateprofile'),
	path('cms/users/changepassword', views.UserChangePassword.as_view(), name = 'userchangepassword'),
	# path('cms/users/newpassword', views.NewPassword.as_view(), name = 'usernewpassword'),
	path('cms/users/registercomplaint', views.RegisterComplaint.as_view(), name = 'registercomplaint'),
	path('cms/users/categories/<int:category_id>/all_json_subcategories', views.filterSubcategories.as_view(), name = 'filtersubcategories'),
	path('cms/users/complaintdetails/<int:complaint_id>', views.ComplaintDetails.as_view(), name = 'complaintdetails'),
	path('cms/users/complaintreport', views.UserReport.as_view(), name = 'complaintreport'),

	path('cms/dept', views.DepNotProcessComplaints.as_view(), name = 'department'),

	#####################department urls #################
	path('cms/department/notprocessed', views.DepNotProcessComplaints.as_view(), name = 'depnotprocessed'),
	path('cms/department/closed', views.DepClosedComplaints.as_view(), name = 'depclosed'),
	path('cms/department/inprocess', views.DepInProcessComplaints.as_view(), name = 'depinprocess'),
	path('cms/department/complaintdetails/<int:complaint_id>', views.DepComplaintDetails.as_view(), name = 'depcomplaintdetails'),
	path('cms/department/updatecomplaint/<int:complaint_id>', views.DepUpdateState.as_view(), name = 'depupdatestate'),


]

complaint/complaint/urls.py
from django.contrib import admin
from django.urls import path, include
from cms import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', include('cms.urls'))
]

complaint/cms/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Admin, Complainants, Category, Subcategory, Complaints, ComplaintRemark
class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={
        	'class': 'form-control',
        	'placeholder': 'Username'
        	 }
        ))
    # first_name = forms.CharField(max_length=150, widget=forms.TextInput(
    #     attrs={
	   #      'class': 'form-control', 
	   #      'placeholder': 'first name'
	   #      }
    #     ))
    # last_name = forms.CharField(max_length=150, widget=forms.TextInput(
    #     attrs={
    #     	'class': 'form-control',
    #     	'placeholder': 'last name'
    #     	}
    #     ))
    email = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={
        	'class': 'form-control', 
        	'type': 'email', 
        	'placeholder': 'email address'
        	}
        ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
        	'class': 'form-control',
        	'placeholder': 'password'
        	}
        ))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.ModelForm):
	username = forms.CharField(max_length = 50, widget = forms.TextInput(
			attrs ={
				'placeholder': 'UserId',
				'class':'form-control',
				'autofocus':'True'
			}
		))
	password = forms.CharField(widget = forms.PasswordInput(
			attrs = {
				'class':'form-control',
				'placeholder':'Password',
				'autofocus':'True'
			}
		))
	class Meta:
		model = User
		fields = ['username','password']

	def validate_username(self):
		pass

class Forgotpass(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(
        attrs = {
            'class':'form-control',
            'placeholder':'Password',
            'autofocus':'True'
            }
        ))
    confirm_password = forms.CharField(widget = forms.PasswordInput(
            attrs = {
                'class':'form-control',
                'placeholder':'Password',
                'autofocus':'True'
            }
        ))
    class Meta:
        model = User
        fields = ['password','confirm_password']

complaint/cms/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from . import forms
from django.http import HttpResponse, JsonResponse
from .models import Admin, Complainants, Category, Subcategory, Complaints, ComplaintRemark
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, update_session_auth_hash, authenticate
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.core.paginator import Paginator
import json
from django.core import serializers
from .utils import render_to_pdf


class Login(View):
    form_class = forms.LoginForm
    template = "cms/login.html"

    def get(self, request):
    	if request.user.is_authenticated:
        	username = request.user
        	admin = Admin.objects.filter(admin_id=username).exists()
        	complainant = Complainants.objects.filter(complainant_id=username).exists()
        	department = Category.objects.filter(category_name = username).exists()
        	print(department)
        	if admin:
        		return redirect('cms:notprocessedcomplaints')
        	elif complainant:
        		return redirect('cms:dashboard')
        	elif department:
        		return redirect('cms:depnotprocessed')
        	else:
        		pass
    	else:
        	form = self.form_class(None)
        	return render(request, self.template, {'form': form})

    def post(self, request):
    	user_name = request.POST['username']
    	password = request.POST['password']
    	user = authenticate(request, username = user_name, password = password)
    	if user is not None:
    		login(request, user)
    		admin = Admin.objects.filter(admin_id=user_name).exists()
    		complainant = Complainants.objects.filter(complainant_id=user_name).exists()
    		department = Category.objects.filter(category_name = user_name).exists()
    		if admin:
    			return redirect('cms:notprocessedcomplaints')
    		elif complainant:
    			return redirect('cms:dashboard')
    		elif department:
    			return redirect('cms:depnotprocessed')
    		else:
    			pass
    	else:
    		form = self.form_class(None)
    		message = 'Incorrect username/password'
    		context = {
    			'form' : form,
    			'message' : message
			}
    		return render(request, self.template, context)

class Logout(View):
	def get(self, request):
		logout(request)
		return redirect('cms:login')

class Register(View):
	form_class = forms.RegisterForm
	template = 'cms/register.html'

	def get(self, request):
		form = self.form_class(None)
		context = {
			'form' : form,
		}
		return render(request, self.template, context)
	def post(self, request):
		form = self.form_class(request.POST)
		# if form.is_valid():
		username = request.POST['username']
		admin = Admin.objects.filter(admin_id = username).exists()
		department = Category.objects.filter(category_name = username).exists()
		user = Complainants.objects.filter(complainant_id = username).exists()
		if admin or department or user:
			email = request.POST['email']
			password = request.POST['password']
			print(email)
			exist = User.objects.filter(username = username).exists()
			if exist:
				context = {
					'form' : form,
					'message' : "You already have an existing account",
				}
				return render(request, self.template, context)
			else:
				user = User.objects.create_user(username, email, password)
				user.save()
				return redirect('cms:login')
		else:
			context = {
				'message' : "You cannot create an account, Please contact the admin for assistance",
				'form' : form,
			}
			return render(request, self.template, context)

class Index(View):
    template = "cms/index.html"
    
    def get(self, request):
    	return render(request, self.template)

class numbers(UserPassesTestMixin, View):
	template = 'cms/admin/base.html'

	def test_func(self):
		user = request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		i_status = 'in process'
		c_status = 'closed'
		numberofinprocess_complaints = ComplaintDetails.objects.filter(status = i_status).count()
		numberofnotprocessed_complaints = ComplaintDetails.objects.filter(status__isnull = True).count()
		numberofclosed_complaints = ComplaintDetails.objects.filter(status = c_status).count()
		context = {
			'numberofinprocess_complaints' : numberofinprocess_complaints,
			'numberofnotprocessed_complaints' : numberofnotprocessed_complaints,
			'numberofclosed_complaints' : numberofclosed_complaints
			}
		print(context)
		return render(request, self.template, context)

class InProcessComplaints(UserPassesTestMixin, View):
	login_url = settings.LOGIN_URL
	template = 'cms/admin/inprocess-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		status = 'in process'
		inprocess_complaints = Complaints.objects.filter(status = status)
		context = {
			'inprocess_complaints': inprocess_complaints
			}
		return render(request, self.template, context)


class NotProcessedComplaints(UserPassesTestMixin, View):
	template = 'cms/admin/notprocessed-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		notprocessed_complaints = Complaints.objects.filter(status__isnull = True)
		context = {
			'notprocessed_complaints': notprocessed_complaints
			}
		return render(request, self.template, context)


class ClosedComplaints(UserPassesTestMixin, View):
	template = 'cms/admin/closed-complaints.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		status = 'closed'
		closed_complaints = Complaints.objects.filter(status = status)
		context = {
			'closed_complaints': closed_complaints
			}
		return render(request, self.template, context)


class ManageUsers(UserPassesTestMixin, View):
	template = 'cms/admin/manage-users.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		complainants = Complainants.objects.all()
		context = {
			'complainants': complainants
			}
		return render(request, self.template, context)


class ManageCategories(UserPassesTestMixin, View):
	template = 'cms/admin/category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		categories = Category.objects.all()
		context = {
			'categories': categories	
			}
		return render(request, self.template, context)


class NewCategory(UserPassesTestMixin, View):
	template = 'cms/admin/category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def post(self, request):
		new_cat = request.POST.get('category')
		cat_description = request.POST.get('description')
		Category.objects.create(category_name = new_cat, category_description = cat_description)
		categories = Category.objects.all()
		context = {
			'categories': categories	
			}
		return render(request, self.template, context)


class ManageSubCategories(UserPassesTestMixin, View):
	template = 'cms/admin/subcategory.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		subcategories = Subcategory.objects.all()
		categories = Category.objects.all()
		context = {
			'subcategories': subcategories,
			'categories': categories	
			}
		return render(request, self.template, context)

class NewSubcategory(UserPassesTestMixin, View):
	template = 'cms/admin/subcategory.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def post(self, request):
		print(request.GET)
		print(request.POST)
		cat_id = request.POST.get('category')
		subcat_name = request.POST.get('subcategory')
		Subcategory.objects.create(category_id_id = cat_id,subcategory_name = subcat_name)
		subcategories = Subcategory.objects.all()
		categories = Category.objects.all()
		context = {
			'subcategories': subcategories,
			'categories': categories	
			}
		return render(request, self.template, context)

class ChangePassword(UserPassesTestMixin, View):
	template = 'cms/admin/change-password.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request):
		return render(request, self.template)

class AdminComplaintDetails(UserPassesTestMixin, View):
	template = 'cms/admin/complaint-details.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request, complaint_id):
		cmpl_details = Complaints.objects.filter(complaint_id = complaint_id)
		cmpl_remark =  ComplaintRemark.objects.filter(complaint_id = complaint_id)
		if cmpl_remark:
			for rmrk in cmpl_remark:
				remark = rmrk.remark
				remarkdate = rmrk.remark_date
		else:
			remark = "No remark"
			remarkdate = "No remark"

		context = {
			'cmpl_details' : cmpl_details,
			'complaint_id' : complaint_id,
			'remark' : remark,
			'remarkdate' : remarkdate,
		}
		return render(request, self.template, context)

class EditCategory(UserPassesTestMixin, View):
	template = 'cms/admin/edit-category.html'

	def test_func(self):
		user = self.request.user
		return Admin.objects.filter(admin_id = user).exists()

	def get(self, request, category_id):
		category = Category.objects.filter(category_id = category_id)
		context = {
			'category' : category
		}
		return render(request, self.template, context)

	def post(self, request, category_id):
		cat_name = request.POST.get('category')
		cat_description = request.POST.get('description')

complaint/cms/templates/cms/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} CMS | User {% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block links %}
    <link rel="stylesheet" href="{% static  'cms/bootstrap-3.3.6/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static  'cms/Font-Awesome-master/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static  'cms/users/assets/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static  'cms/users/assets/font-awesome/css/font-awesome.css' %}" >
    <link href="{% static  'cms/admin/css/theme.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static  'cms/users/assets/css/to-do.css'%}">
    <link rel="stylesheet" href="{% static  'cms/users/assets/css/table-responsive.css'%}">
    <link rel="stylesheet" href="{% static  'cms/users/assets/css/zabuto_calendar.css'%}">
    <link rel="stylesheet" href="{% static  'cms/users/assets/css/style.css'%}">
    <link rel="stylesheet" href="{% static  'cms/users/assets/css/style-responsive.css'%}">
    {% endblock %}
    <style type="text/css">
        .header .nav>li>a {
            padding: 20px 15px;
            font-weight: bold;
            color: #777;
        }
        .header .nav>li.active , .header .nav>li.active , .header .nav>li.active, .header .nav>li:hover  {
            background: #f9f9f9;
        }
        .header .nav>li.dropdown.open>.dropdown-toggle, .header .nav>li.dropdown.active>.dropdown-toggle, .header .nav>li.dropdown.open.active>.dropdown-toggle {
            background: #fff;
            border-left: 1px solid #ddd;
            border-right: 1px solid #ddd;
            padding-left: 14px;
            padding-right: 14px;
            position: relative;
            z-index: 9999;
            padding-bottom: 0px;
        }
        .header .nav>li>.dropdown-menu {
            border: 1px solid #ccc;
            -webkit-border-radius: 0 0 3px 3px;
            -moz-border-radius: 0 0 3px 3px;
            border-radius: 0 0 3px 3px;
            -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.1);
            -moz-box-shadow: 0 1px 1px rgba(0,0,0,0.1);
            box-shadow: 0 1px 1px rgba(0,0,0,0.1);
            left: -1px;
            min-width: 200px;
            margin: -1px 0 0;
            z-index: 9991
        }
        .header .nav>li>.dropdown-menu::before, .header .nav>li>.dropdown-menu::after {
            display: none
        }
        .header .nav>li>.dropdown-menu li>a {
            padding: 10px 20px
        }
        .header .nav>li>.dropdown-menu li>a:hover {
            background: #f9f9f9;
            color: #555;

        }

        .header .nav>.active>a, .header .nav>.active>a:hover, .header .nav>.active>a:focus
        {
            
        -webkit-box-shadow: none;
        -moz-box-shadow: none;
        box-shadow: none;
            }
        .header .nav.nav-icons>li>a {
            background: none;
            -webkit-box-shadow:none;
            -moz-box-shadow: none;
            box-shadow: none;
            color: #777;
            font-weight: bold;
            padding: 5px;
            margin: 15px 5px
        }
        .header .pull-right>li>.dropdown-menu, .header .nav>li>.dropdown-menu.pull-right {
            right: 0;
            left: auto
        }
        .header .divider-vertical {
            background: #eee;
            border-left: 0;
            border-right: 0;
            height: 30px;
            margin: 25px 15px;
            width: 1px
        }
        .nav-user>a {
            height: 30px
        }
        .nav-avatar {
            width: 34px;
            height: 34px;
            margin: -7px 5px 0 0;
            -webkit-border-radius: 50%;
            -moz-border-radius: 50%;
            border-radius: 50%
        }
        .dropdown-menu {
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            border-radius: 3px
        }
    </style>
</head>

<body>
    <section id="container">
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>Complaint Management System</b></a>
                
            <!-- <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="{% url 'cms:logout' %}">Logout</a></li>
                </ul>
            </div> -->
            <div class="nav-collapse collapse navbar-inverse-collapse">
                <ul class="nav pull-right">
                    <li class="nav-user dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'cms/admin/images/user.png' %}" class="nav-avatar" />
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'cms:changepassword' %}">Change Password</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'cms:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </header>
        <aside>
            <div id="sidebar"  class="nav-collapse ">
                <ul class="sidebar-menu" id="nav-accordion">
                    <p class="centered"><a href="profile.html"><img src="{% static 'cms/users/assets/img/ui-sam.jpg' %}" class="img-circle" width="60"></a></p>
                    <h5 class="centered">{{ request.user }}</h5>

                    <li class="mt">
                        <a href="{% url 'cms:dashboard' %}">
                            <i class="fa fa-dashboard"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" >
                            <i class="fa fa-cogs"></i>
                            <span>Account Setting</span>
                        </a>
                        <ul class="sub">
                            <li><a  href="{% url 'cms:profile' %}">Profile</a></li>
                            <li><a  href="{% url 'cms:userchangepassword' %}">Change Password</a></li>
                        </ul>
                    </li>
                        <li class="sub-menu">
                            <a href="{% url 'cms:registercomplaint' %}" >
                                <i class="fa fa-book"></i>
                                <span>Lodge Complaint</span>
                            </a>
                        </li>
                    </li>  
                    <li class="sub-menu">
                        <a class="active" href="{% url 'cms:complaintreport' %}" >
                            <i class="fa fa-envelope"></i>
                            <span>Complaint Report</span>
                        </a>   
                    </li> 
                    <li class="sub-menu">
                        <a class="active" href="{% url 'cms:complainthistory' %}" >
                            <i class="fa fa-tasks"></i>
                            <span>Complaint History</span>
                        </a>   
                    </li>
                </ul>
            </div>
        </aside>
        <section id="main-content">
            <section class="wrapper">
                {% block content %}
                
                {% endblock %}
            </section>
        </section>
    </section>
{% block scripts %}
<script src="{% static 'cms/users/assets/js/jquery.js' %}"></script>
<script src="{% static 'cms/users/assets/js/bootstrap.min.js' %}"></script>
<script class="include" type="text/javascript" src="{% static 'cms/users/assets/js/jquery.dcjqaccordion.2.7.js' %}"></script>
<script src="{% static 'cms/users/assets/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'cms/users/assets/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
<!--common script for all pages-->
<script src="{% static 'cms/users/assets/js/common-scripts.js' %}"></script>
<!--script for this page-->
<script src="{% static 'cms/users/assets/js/jquery-ui-1.9.2.custom.min.js' %}"></script>
<!--custom switch-->
<script src="{% static 'cms/users/assets/js/bootstrap-switch.js' %}"></script>
<!--custom tagsinput-->
<script src="{% static 'cms/users/assets/js/jquery.tagsinput.js' %}"></script>
<!--custom checkbox & radio-->
<script type="text/javascript" src="{% static 'cms/users/assets/js/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'cms/users/assets/js/bootstrap-daterangepicker/date.js' %}"></script>
<script type="text/javascript" src="{% static 'cms/users/assets/js/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'cms/users/assets/js/bootstrap-inputmask/bootstrap-inputmask.min.js' %}"></script>
<script src="{% static 'cms/users/assets/js/form-component.js' %}"></script> 
{% endblock %}
</body>

</html>

complaint/cms/templates/cms/users/complaint-history.html
{% extends 'cms/users/base.html' %}
{% load static %}
{% block title %}User | complaints history{% endblock %}
{% block links %}
    <link href="{% static 'cms/users/assets/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'cms/users/assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'cms/users/assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'cms/users/assets/css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'cms/users/assets/css/table-responsive.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h3><i class="fa fa-angle-right"></i>Your Complaint History</h3>
<div class="row mt">
	<div class="col-lg-12">
  		<div class="content-panel">
			<section id="unseen">
				<table class="table table-bordered table-striped table-condensed">
					<thead>
						<tr>
							<th>Complaint #ID</th>
							<th>Reg Date</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
				    
				    <tbody>
				    {% for complaint in complainthistory %}
					    <tr>
					        <td align="center">{{ complaint.complaint_id }}</td>
					        <td align="center">{{ complaint.reg_date }}</td>
					        <td align="center">
					            {% if complaint.status == null %}
					           		<button type="button" class="btn btn-theme04">Not Process Yet</button>
					            {% endif %}
					            {% if complaint.status == 'in process' %}
									<button type="button" class="btn btn-warning">In Process</button>
					            {% endif %}
					            {% if complaint.status == 'closed' %}
									<button type="button" class="btn btn-success">Closed</button>
								{% endif %}

					        <td align="center">
						        <a href="{% url 'cms:complaintdetails'  complaint.complaint_id %}">
									<button type="button" class="btn btn-primary">View Details</button>
								</a>
					        </td>
					    </tr>
					{% endfor %}
				    </tbody>
				</table>
			</section>
		</div><!-- /content-panel -->
	</div><!-- /col-lg-4 -->			
</div><!-- /row -->
{% endblock %}

{% block scripts %}
    <script src="{% static 'cms/users/assets/js/jquery.js' %}"></script>
    <script src="{% static 'cms/users/assets/js/bootstrap.min.js' %}"></script>
    <script class="include" type="text/javascript" src="{% static 'cms/users/assets/js/jquery.dcjqaccordion.2.7.js' %}"></script>
    <script src="{% static 'cms/users/assets/js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'cms/users/assets/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <!--common script for all pages-->
    <script src="{% static 'cms/users/assets/js/common-scripts.js' %}"></script>
{% endblock %}

complaint/cms/templates/cms/users/dept.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% for x in inprocess_complaints %}
	{{ x.category_id.category_name }}
	{% endfor %}
</body>
</html>

complaint/cms/templates/cms/users/index.html
{% extends 'cms/users/base.html' %}
{% load static %}
{% block links %}{% endblock %}
{% block content %}{% endblock %}
{% block scripts %}{% endblock %}

complaint/cms/templates/cms/users/logout.html
{% extends 'cms/users/base.html' %}
{% load static %}
{% block links %}{% endblock %}
{% block content %}{% endblock %}
{% block scripts %}{% endblock %}

complaint/cms/templates/cms/users/registration.html
{% extends 'cms/users/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block links %}{% endblock %}
{% block content %}{% endblock %}
{% block scripts %}{% endblock %}